language: rust

sudo: required

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      rust: nightly

env:
  - CODECOV_TOKEN="4dad02c5-a383-4b0f-a78d-1d80f7ca8662"

rust:
  - stable
  - nightly

jobs:
  include:
      - stage: test
        script:
          - cargo clippy --all-targets --all-features -- -D warnings
          - cargo test --verbose --all
        before_script:
          - rustup component add clippy
      - stage: coverage
        rust: nightly
        before_install:
          - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
        script:
          - export CARGO_INCREMENTAL=0
          - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
          - cargo build --verbose $CARGO_OPTIONS
          - cargo test --verbose $CARGO_OPTIONS
          - |
            zip -0 ccov.zip `find . \( -name "historical_chrono*.gc*" \) -print`;
            ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
            bash <(curl -s https://codecov.io/bash) -f lcov.info;
      - stage: build
        script: cargo build --verbose --all

branches:
  only:
    - master
